name: 'Setup Node & pnpm'
description: 'Sets up Node.js and pnpm with caching for faster installations'

inputs:
  node-version-file:
    description: 'File containing the Node.js version to use'
    required: false
    default: 'package.json'
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
  frozen-lockfile:
    description: 'Whether to use --frozen-lockfile with pnpm install'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
        package_json_file: ${{ inputs.node-version-file }}

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      if: ${{ inputs.install-deps == 'true' }}
      shell: bash
      run: |
        # The server package.json has jsdom as a dependency that's added later
        # Avoid frozen lockfile to prevent errors when CI adds it
        if [[ "${{ inputs.frozen-lockfile }}" == "true" ]]; then
          pnpm install --no-frozen-lockfile
        else
          pnpm install
        fi
