version: '3.8'

services:
  server:
    image: ghcr.io/cbnsndwch/react-router-nest-server:${TAG:-latest}
    restart: always

    # healthcheck:
    #   retries: 3
    #   interval: 30s
    #   timeout: 10s
    #   start_period: 15s
    #   test:
    #     - 'CMD'
    #     - 'wget'
    #     - '--quiet'
    #     - '--tries=1'
    #     - '--spider'
    #     - 'http://localhost:3000/health'

    # Optional resource limits
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G
    #     reservations:
    #       cpus: '0.25'
    #       memory: 256M

    environment:
      - NODE_ENV=production

      # App configuration
      - APP_PORT=3000
      - APP_HOST=0.0.0.0

      # Domain for external access (used in URLs)
      - APP_DOMAIN=${DOMAIN}
      - SERVER_PORT=${SERVER_PORT:-4003}

    ports:
      # Map to a host port (adjust as needed)
      - ${SERVER_PORT:-4003}:${SERVER_PORT:-4003}

    # Optional volume for persistent data
    # volumes:
    #   - server_data:/app/data

    networks:
      - proxy

networks:
  proxy:
    external: true
